# Generated by Django 5.0.3 on 2024-03-21 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTVShow',
            fields=[
                ('Show_id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Release_date', models.DateField()),
                ('Description', models.TextField()),
                ('Duration', models.PositiveIntegerField()),
                ('Views', models.PositiveIntegerField(default=0)),
                ('Country', models.CharField(max_length=50)),
                ('Rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Genre', models.CharField(max_length=50)),
                ('Actor', models.CharField(max_length=100)),
                ('Actress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_duration', models.PositiveIntegerField()),
                ('plan_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=100)),
                ('Email_id', models.EmailField(max_length=254, unique=True)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('Phone_number', models.CharField(max_length=15)),
                ('Plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='live_streaming.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('Payment_time', models.DateTimeField(auto_now_add=True)),
                ('Payment_date', models.DateField()),
                ('Payment_method', models.CharField(max_length=50)),
                ('Amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='live_streaming.plan')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='live_streaming.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Watches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live_streaming.movietvshow')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live_streaming.useraccount')),
            ],
            options={
                'unique_together': {('User', 'Show')},
            },
        ),
    ]
