# Generated by Django 5.0.3 on 2024-03-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_streaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Transaction_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
