# Generated by Django 5.0.3 on 2024-03-24 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_streaming', '0004_movietvshow_video'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watches',
            unique_together=set(),
        ),
    ]
